import { Link } from "react-router-dom";
import { Shield, FileText, Lock, BrainCircuit } from "lucide-react";

export const DisclaimerSection = () => {
  return (
    <section className="border-t border-border bg-muted/20">
      <div className="container mx-auto px-6 py-16 md:py-24">
        <div className="mx-auto max-w-3xl">
          {/* Badge */}
          <div className="flex justify-center mb-8">
            <div className="inline-flex items-center gap-2 rounded-full border border-primary/20 bg-primary/5 px-4 py-1.5 text-xs font-semibold uppercase tracking-wider text-primary">
              <Shield className="h-3.5 w-3.5" />
              Professional Use Only
            </div>
          </div>

          {/* Heading */}
          <h2 className="text-center font-display text-2xl md:text-3xl font-bold tracking-tight text-foreground mb-8">
            A quick but important note.
          </h2>

          {/* Disclaimer body */}
          <div className="rounded-2xl border border-border bg-card p-8 md:p-10 shadow-sm">
            <div className="space-y-5 text-sm leading-relaxed text-muted-foreground">
              <p className="text-foreground font-medium">
                Licensify AI is an AI powered legal tool designed exclusively for use by qualified legal professionals including lawyers, solicitors, barristers, and licensed legal practitioners. It is not designed for use by members of the general public as a substitute for legal advice.
              </p>

              <p>
                Licensify AI is not a law firm and does not provide legal advice. Nothing generated by Licensify AI should be taken as legal advice or used as a substitute for consultation with a qualified legal professional. All outputs are AI generated and should be independently reviewed and verified by a licensed attorney before use in any real legal matter.
              </p>

              <p>
                By using Licensify AI you confirm that you are a qualified legal professional or are working under the supervision of one, and you acknowledge that outputs require independent professional verification before any legal reliance is placed on them.
              </p>

              <p className="text-foreground font-medium">
                Use it as a powerful starting point. Not as a final answer.
              </p>
            </div>

            {/* Divider */}
            <div className="my-8 border-t border-border" />

            {/* Policy links */}
            <div className="flex flex-wrap items-center justify-center gap-x-6 gap-y-3">
              <Link
                to="/terms"
                className="inline-flex items-center gap-1.5 text-xs font-medium text-muted-foreground hover:text-primary transition-colors"
              >
                <FileText className="h-3.5 w-3.5" />
                Terms of Service
              </Link>
              <span className="hidden sm:inline text-border">|</span>
              <Link
                to="/privacy"
                className="inline-flex items-center gap-1.5 text-xs font-medium text-muted-foreground hover:text-primary transition-colors"
              >
                <Lock className="h-3.5 w-3.5" />
                Privacy Policy
              </Link>
              <span className="hidden sm:inline text-border">|</span>
              <Link
                to="/ai-usage-policy"
                className="inline-flex items-center gap-1.5 text-xs font-medium text-muted-foreground hover:text-primary transition-colors"
              >
                <BrainCircuit className="h-3.5 w-3.5" />
                AI Usage Policy
              </Link>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};
